# -*- coding: utf-8 -*-
"""Exercício I (Python) - Pesquisa Acadêmica

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17do6FqoEdgEXLmC1M9Q1U_z_zwUqbrAL
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dados = pd.read_csv('Pesquisa.csv')
x = dados.iloc[:, :-1].values
y = dados.iloc[:, -1].values

print(x)

print(y)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

print(x)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

print(y)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

print(x_train)

print(x_test)

print(y_train)

print(y_test)

from sklearn.preprocessing import StandardScaler
sd = StandardScaler()
x_train[:, 4:] = sd.fit_transform(x_train[:, 4:])
x_test[:, 4:] = sd.transform(x_test[:, 4:])

print(x_train)

print(x_test)